sonar.organization=jtr220
sonar.projectKey=JTR220_spring-boot-bloc3

# Analyse uniquement le code "prod"
sonar.sources=core,loader,cli,module,platform,starter,configuration-metadata

# Exclusions globales
sonar.exclusions=**/.github/**,**/documentation/**,**/antora/**,**/*.adoc,**/build/**,**/.gradle/**,buildSrc/**,build-logic/**,build-plugin/**,buildpack/**

sonar.test.exclusions=**/src/test/**,integration-test/**,smoke-test/**,system-test/**,test-support/**
sonar.coverage.exclusions=**/src/test/**,integration-test/**,smoke-test/**,system-test/**,test-support/**
